var $=function(s,r){return (r||document).querySelector(s)};var $$=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))};
var cases=[{title:'Technical cleanup for a service marketplace',tags:['Technical SEO','GA4/GSC'],metric:'+38% qualified organic leads',note:'Fixed index bloat, weak canonicals, orphaned services, and missing event visibility.'},{title:'Content moat for Malaysia founder queries',tags:['Content SEO'],metric:'42 briefs mapped',note:'Built topic clusters around founder pain points, AI SEO, and service-intent landing pages.'},{title:'Backlink risk and gap review',tags:['Backlink Audit'],metric:'3-tier link priority map',note:'Separated cleanup candidates, authority gaps, and practical outreach opportunities.'},{title:'GSC diagnosis for a launch dip',tags:['GA4/GSC','Technical SEO'],metric:'7-day recovery plan',note:'Compared templates, query classes, crawl status, and page-level click loss.'},{title:'iGaming SEO content architecture',tags:['iGaming SEO','Content SEO'],metric:'SEA market taxonomy',note:'Designed compliant clusters for review, comparison, glossary, and long-tail intent pages.'},{title:'SEM-to-SEO landing page alignment',tags:['Content SEO','GA4/GSC'],metric:'lower CPC waste',note:'Matched paid search intent to landing page sections, FAQs, and conversion tracking.'}];
function initTabs(){$$('.tab').forEach(function(tab){tab.onclick=function(){$$('.tab').forEach(function(t){t.classList.toggle('active',t===tab)});$$('.panel').forEach(function(p){p.classList.toggle('active',p.dataset.panel===tab.dataset.tool)})}})}
function initSerp(){function u(){var t=$('#metaTitle').value.trim(),d=$('#metaDescription').value.trim();$('#serpTitle').textContent=t||'Your SEO title appears here';$('#serpDescription').textContent=d||'Your meta description appears here.';$('#serpMeter').textContent='Title: '+t.length+' chars | Description: '+d.length+' chars'}['metaTitle','metaDescription'].forEach(function(id){$('#'+id).addEventListener('input',u)});u()}
function initIntent(){var keys={Informational:['how','what','guide','learn','checklist','why','ideas'],Commercial:['best','top','compare','review','consultant','specialist'],Transactional:['hire','buy','price','cost','package','book'],Diagnostic:['drop','audit','fix','recover','error','issue']};$('#sortIntent').onclick=function(){var lines=$('#keywordList').value.split('\n').map(function(x){return x.trim()}).filter(Boolean);var grouped={Informational:[],Commercial:[],Transactional:[],Diagnostic:[],Exploratory:[]};lines.forEach(function(k){var low=k.toLowerCase(),hit='Exploratory';Object.keys(keys).some(function(b){if(keys[b].some(function(w){return low.indexOf(w)>=0})){hit=b;return true}return false});grouped[hit].push(k)});$('#intentResults').innerHTML=Object.keys(grouped).map(function(b){return '<section class="bucket"><h3>'+b+'</h3><ul>'+(grouped[b].length?grouped[b]:['No keywords yet']).map(function(w){return '<li>'+w+'</li>'}).join('')+'</ul></section>'}).join('')};$('#sortIntent').click()}
function initAudit(){$('#buildAudit').onclick=function(){var items=['Crawl priority pages and blocked paths','Check indexability, canonicals, redirects, and status codes','Review internal link depth and orphan pages','Compare clicks, impressions, CTR, and position by page','Map search intent by funnel stage','Turn findings into a 30-day action board'];$('#auditOutput').innerHTML='<h3>SEO audit checklist</h3><ul>'+items.map(function(i){return '<li>'+i+'</li>'}).join('')+'</ul>'};$('#buildAudit').click()}
function initBrief(){$('#buildBrief').onclick=function(){var k=$('#briefKeyword').value.trim()||'SEO strategy';$('#briefOutput').innerHTML='<h3>'+k+'</h3><ul><li>Angle: make the topic practical for Malaysia and SEA decision-makers.</li><li>Must answer: what changed, why it matters, what to check first, and when to ask for help.</li><li>Suggested sections: definition, symptoms, process, examples, tools, FAQ, CTA.</li><li>Conversion module: offer a mini audit, discovery call, or downloadable checklist.</li></ul>'};$('#buildBrief').click()}
function initDrop(){$('#diagnoseDrop').onclick=function(){var c=$('#dropChange').value.trim()||'recent site change';var items=['Check tracking, noindex changes, robots.txt, redirects, and migration mistakes.','Compare the exact drop date with deployments and Google updates.','Group pages by template and query class to find the weakening cluster.'];$('#dropOutput').innerHTML='<h3>Traffic drop diagnostic</h3><p>Recent change: '+c+'</p><ul>'+items.map(function(x){return '<li>'+x+'</li>'}).join('')+'</ul>'};$('#diagnoseDrop').click()}
function initQuiz(){$('#quizResult').onclick=function(){var res=['Technical Detective: you find the crawl clue everyone else missed.','Content Cartographer: you turn messy demand into a clean topic map.','Analytics Alchemist: you connect data, behavior, and decisions.','Founder Whisperer: you translate search demand into business direction.'];$('#quizAnswer').textContent=res[Math.floor(Math.random()*res.length)]}}
function renderCases(f){var arr=f==='All'||!f?cases:cases.filter(function(c){return c.tags.indexOf(f)>=0});$('#caseGrid').innerHTML=arr.map(function(c){return '<article class="case"><span class="metric">'+c.metric+'</span><h3>'+c.title+'</h3><p>'+c.note+'</p><div class="tags">'+c.tags.map(function(t){return '<span class="tag">'+t+'</span>'}).join('')+'</div></article>'}).join('')}function initFilters(){$$('.filter').forEach(function(b){b.onclick=function(){$$('.filter').forEach(function(x){x.classList.toggle('active',x===b)});renderCases(b.dataset.filter)}});renderCases('All')}
function initContact(){$('#contactForm').onsubmit=function(e){e.preventDefault();var body='Name: '+$('#contactName').value+'\nEmail: '+$('#contactEmail').value+'\nInterested in: '+$('#contactInterest').value+'\n\n'+$('#contactMessage').value;location.href='mailto:vannesang97@gmail.com?subject=Hui%20Chen%20SEO%20Playground%20Enquiry&body='+encodeURIComponent(body)}}
initTabs();initSerp();initIntent();initAudit();initBrief();initDrop();initQuiz();initFilters();initContact();
